Data:
  data_root: ../data/VOCdevkit2012/VOC2012
  train_list: ./lists/pascal/voc_sbd_merge_noduplicate.txt
  val_list: ./lists/pascal/val.txt
  classes: 1


Train:
  # Aug
  train_h: 473
  train_w: 473
  val_size: 473
  scale_min: 0.9  # minimum random scale
  scale_max: 1.1 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255

  # Dataset & Mode
  split: 0
  shot: 1
  data_set: 'pascal'
  use_split_coco: False # True means FWB setting

  # Optimizer
  batch_size: 16 # batch size for training (bs8 for 1GPU)
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  stop_interval: 75 # stop when the best result is not updated for "stop_interval" epochs
  index_split: -1 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume:   # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  SubEpoch_val: True # val at the half epoch
  fix_random_seed_val: True
  batch_size_val: 1
  resized_val: True
  ori_resize: True  # use original label for evaluation
  # Else
  workers: 8
  fix_bn: True
  manual_seed: 321
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]

Method:
  layers: 50
  vgg: False
  aux_weight: 1.0

Test_Finetune:
  weight:  # load weight for fine-tuning or testing (such as train_epoch_85_0.6318.pth)


